swagger: '2.0'


schemes: 
  - http
  - https
  
host: localhost:8085
basePath: /batybank-api/v1 

info:
  version: 1.0.0
  title: BitBank Api
  description: Administra a movimentação bancária do correntista e controla   acesso através do cpf e senha.
  termsOfService: http://localhost:8085/batybank-api/v1/termo-uso
  contact:
    name: Suporte
    url: http://localhost:8085/batybank-api/v1/suporte
    email: suporte@bytebanckapi.com
  






paths:
  '/cliente':
    post:
      summary: Cadastra cliente
      description: Cadastra um novo cliente
      consumes: 
        - application/json
      produces: 
        - application/json
      operationId: cadastraCliente
      parameters: 
        - in: body
          name: cliente_
          schema:
            type: object
            properties:
              titular: 
                type: string
                example: janete silva
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            type: object
            properties:
              titular: 
                type: string
                example: janete silva
        400:
          description: Requisiçao inválida
        500:
          description: Erro interno no servidor
        
        
    